language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./docs
  github_token: $GITHUB_TOKEN
  keep_history: false
  target_branch: gh-page
  on:
    branch: master
